apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "app.opsboost.io/v1alpha1",
          "kind": "Kubernetes",
          "metadata": {
            "name": "example-kubernetes"
          },
          "spec": {
            "size": 3
          }
        }
      ]
    capabilities: Basic Install
  name: kube-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Kubernetes is the Schema for the kubernetes API
      kind: Kubernetes
      name: kubernetes.app.opsboost.io
      version: v1alpha1
  description: Placeholder description
  displayName: Kube Operator
  install:
    spec:
      deployments:
      - name: kube-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: kube-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: kube-operator
            spec:
              containers:
              - command:
                - kube-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: kube-operator
                image: quay.io/opsboost/kube-operator
                imagePullPolicy: Always
                name: kube-operator
                resources: {}
              serviceAccountName: kube-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - kube-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - app.opsboost.io
          resources:
          - '*'
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: kube-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: kube-operator.v0.0.0
  version: 0.0.1
